name: Garmo
favicon: null
layout_spectrum: 0.22549
typography_spectrum: 0.73964
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5
  lightness: 0.7083522854372859
  saturation: 0.5914218828547746
  rhythmicContrast: 0.1311982898041606
purpose: []
